package cn.isnap.melon.dao;

import cn.isnap.melon.model.CarSeries;

public interface CarSeriesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_series
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_series
     *
     * @mbggenerated
     */
    int insert(CarSeries record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_series
     *
     * @mbggenerated
     */
    int insertSelective(CarSeries record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_series
     *
     * @mbggenerated
     */
    CarSeries selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_series
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CarSeries record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_series
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CarSeries record);
}