package cn.isnap.melon.dao;

import cn.isnap.melon.model.CarType;

public interface CarTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String levelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_type
     *
     * @mbggenerated
     */
    int insert(CarType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_type
     *
     * @mbggenerated
     */
    int insertSelective(CarType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_type
     *
     * @mbggenerated
     */
    CarType selectByPrimaryKey(String levelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CarType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CarType record);
}