package cn.isnap.melon.model;

public class CarBrand {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_brand.id
     *
     * @mbggenerated
     */
    private Short id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_brand.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_brand.image
     *
     * @mbggenerated
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_brand.pinyin
     *
     * @mbggenerated
     */
    private String pinyin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_brand.fetch_url
     *
     * @mbggenerated
     */
    private String fetchUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_brand.created_at
     *
     * @mbggenerated
     */
    private Integer createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_brand.updated_at
     *
     * @mbggenerated
     */
    private Integer updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_brand.deleted_at
     *
     * @mbggenerated
     */
    private Integer deletedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_brand.channel
     *
     * @mbggenerated
     */
    private Byte channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_brand.flag
     *
     * @mbggenerated
     */
    private Byte flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_brand.pbid
     *
     * @mbggenerated
     */
    private Integer pbid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_brand.channel_2
     *
     * @mbggenerated
     */
    private String channel2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_brand.new_title
     *
     * @mbggenerated
     */
    private String newTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_brand.liyang_id
     *
     * @mbggenerated
     */
    private String liyangId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_brand.last_updated_at
     *
     * @mbggenerated
     */
    private Integer lastUpdatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_brand.last_updated_user
     *
     * @mbggenerated
     */
    private String lastUpdatedUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.id
     *
     * @return the value of car_brand.id
     *
     * @mbggenerated
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.id
     *
     * @param id the value for car_brand.id
     *
     * @mbggenerated
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.title
     *
     * @return the value of car_brand.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.title
     *
     * @param title the value for car_brand.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.image
     *
     * @return the value of car_brand.image
     *
     * @mbggenerated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.image
     *
     * @param image the value for car_brand.image
     *
     * @mbggenerated
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.pinyin
     *
     * @return the value of car_brand.pinyin
     *
     * @mbggenerated
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.pinyin
     *
     * @param pinyin the value for car_brand.pinyin
     *
     * @mbggenerated
     */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin == null ? null : pinyin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.fetch_url
     *
     * @return the value of car_brand.fetch_url
     *
     * @mbggenerated
     */
    public String getFetchUrl() {
        return fetchUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.fetch_url
     *
     * @param fetchUrl the value for car_brand.fetch_url
     *
     * @mbggenerated
     */
    public void setFetchUrl(String fetchUrl) {
        this.fetchUrl = fetchUrl == null ? null : fetchUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.created_at
     *
     * @return the value of car_brand.created_at
     *
     * @mbggenerated
     */
    public Integer getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.created_at
     *
     * @param createdAt the value for car_brand.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Integer createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.updated_at
     *
     * @return the value of car_brand.updated_at
     *
     * @mbggenerated
     */
    public Integer getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.updated_at
     *
     * @param updatedAt the value for car_brand.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Integer updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.deleted_at
     *
     * @return the value of car_brand.deleted_at
     *
     * @mbggenerated
     */
    public Integer getDeletedAt() {
        return deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.deleted_at
     *
     * @param deletedAt the value for car_brand.deleted_at
     *
     * @mbggenerated
     */
    public void setDeletedAt(Integer deletedAt) {
        this.deletedAt = deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.channel
     *
     * @return the value of car_brand.channel
     *
     * @mbggenerated
     */
    public Byte getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.channel
     *
     * @param channel the value for car_brand.channel
     *
     * @mbggenerated
     */
    public void setChannel(Byte channel) {
        this.channel = channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.flag
     *
     * @return the value of car_brand.flag
     *
     * @mbggenerated
     */
    public Byte getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.flag
     *
     * @param flag the value for car_brand.flag
     *
     * @mbggenerated
     */
    public void setFlag(Byte flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.pbid
     *
     * @return the value of car_brand.pbid
     *
     * @mbggenerated
     */
    public Integer getPbid() {
        return pbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.pbid
     *
     * @param pbid the value for car_brand.pbid
     *
     * @mbggenerated
     */
    public void setPbid(Integer pbid) {
        this.pbid = pbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.channel_2
     *
     * @return the value of car_brand.channel_2
     *
     * @mbggenerated
     */
    public String getChannel2() {
        return channel2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.channel_2
     *
     * @param channel2 the value for car_brand.channel_2
     *
     * @mbggenerated
     */
    public void setChannel2(String channel2) {
        this.channel2 = channel2 == null ? null : channel2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.new_title
     *
     * @return the value of car_brand.new_title
     *
     * @mbggenerated
     */
    public String getNewTitle() {
        return newTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.new_title
     *
     * @param newTitle the value for car_brand.new_title
     *
     * @mbggenerated
     */
    public void setNewTitle(String newTitle) {
        this.newTitle = newTitle == null ? null : newTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.liyang_id
     *
     * @return the value of car_brand.liyang_id
     *
     * @mbggenerated
     */
    public String getLiyangId() {
        return liyangId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.liyang_id
     *
     * @param liyangId the value for car_brand.liyang_id
     *
     * @mbggenerated
     */
    public void setLiyangId(String liyangId) {
        this.liyangId = liyangId == null ? null : liyangId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.last_updated_at
     *
     * @return the value of car_brand.last_updated_at
     *
     * @mbggenerated
     */
    public Integer getLastUpdatedAt() {
        return lastUpdatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.last_updated_at
     *
     * @param lastUpdatedAt the value for car_brand.last_updated_at
     *
     * @mbggenerated
     */
    public void setLastUpdatedAt(Integer lastUpdatedAt) {
        this.lastUpdatedAt = lastUpdatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.last_updated_user
     *
     * @return the value of car_brand.last_updated_user
     *
     * @mbggenerated
     */
    public String getLastUpdatedUser() {
        return lastUpdatedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.last_updated_user
     *
     * @param lastUpdatedUser the value for car_brand.last_updated_user
     *
     * @mbggenerated
     */
    public void setLastUpdatedUser(String lastUpdatedUser) {
        this.lastUpdatedUser = lastUpdatedUser == null ? null : lastUpdatedUser.trim();
    }
}