package cn.isnap.melon.model;

public class CarSeries {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_series.id
     *
     * @mbggenerated
     */
    private Short id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_series.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_series.image
     *
     * @mbggenerated
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_series.brand_id
     *
     * @mbggenerated
     */
    private Short brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_series.firm_id
     *
     * @mbggenerated
     */
    private Byte firmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_series.firm_name
     *
     * @mbggenerated
     */
    private String firmName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_series.car_type
     *
     * @mbggenerated
     */
    private Byte carType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_series.price_low
     *
     * @mbggenerated
     */
    private Integer priceLow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_series.price_hig
     *
     * @mbggenerated
     */
    private Integer priceHig;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_series.car_stat
     *
     * @mbggenerated
     */
    private Byte carStat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_series.fetch_url
     *
     * @mbggenerated
     */
    private String fetchUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_series.created_at
     *
     * @mbggenerated
     */
    private Integer createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_series.updated_at
     *
     * @mbggenerated
     */
    private Integer updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_series.deleted_at
     *
     * @mbggenerated
     */
    private Integer deletedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_series.channel
     *
     * @mbggenerated
     */
    private Byte channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_series.psid
     *
     * @mbggenerated
     */
    private Integer psid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_series.channel_2
     *
     * @mbggenerated
     */
    private String channel2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_series.flag
     *
     * @mbggenerated
     */
    private Byte flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_series.new_title
     *
     * @mbggenerated
     */
    private String newTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_series.new_firm_name
     *
     * @mbggenerated
     */
    private String newFirmName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_series.liyang_id
     *
     * @mbggenerated
     */
    private String liyangId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_series.extra_title
     *
     * @mbggenerated
     */
    private String extraTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_series.last_updated_at
     *
     * @mbggenerated
     */
    private Integer lastUpdatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_series.last_updated_user
     *
     * @mbggenerated
     */
    private String lastUpdatedUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_series.id
     *
     * @return the value of car_series.id
     *
     * @mbggenerated
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_series.id
     *
     * @param id the value for car_series.id
     *
     * @mbggenerated
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_series.title
     *
     * @return the value of car_series.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_series.title
     *
     * @param title the value for car_series.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_series.image
     *
     * @return the value of car_series.image
     *
     * @mbggenerated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_series.image
     *
     * @param image the value for car_series.image
     *
     * @mbggenerated
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_series.brand_id
     *
     * @return the value of car_series.brand_id
     *
     * @mbggenerated
     */
    public Short getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_series.brand_id
     *
     * @param brandId the value for car_series.brand_id
     *
     * @mbggenerated
     */
    public void setBrandId(Short brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_series.firm_id
     *
     * @return the value of car_series.firm_id
     *
     * @mbggenerated
     */
    public Byte getFirmId() {
        return firmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_series.firm_id
     *
     * @param firmId the value for car_series.firm_id
     *
     * @mbggenerated
     */
    public void setFirmId(Byte firmId) {
        this.firmId = firmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_series.firm_name
     *
     * @return the value of car_series.firm_name
     *
     * @mbggenerated
     */
    public String getFirmName() {
        return firmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_series.firm_name
     *
     * @param firmName the value for car_series.firm_name
     *
     * @mbggenerated
     */
    public void setFirmName(String firmName) {
        this.firmName = firmName == null ? null : firmName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_series.car_type
     *
     * @return the value of car_series.car_type
     *
     * @mbggenerated
     */
    public Byte getCarType() {
        return carType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_series.car_type
     *
     * @param carType the value for car_series.car_type
     *
     * @mbggenerated
     */
    public void setCarType(Byte carType) {
        this.carType = carType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_series.price_low
     *
     * @return the value of car_series.price_low
     *
     * @mbggenerated
     */
    public Integer getPriceLow() {
        return priceLow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_series.price_low
     *
     * @param priceLow the value for car_series.price_low
     *
     * @mbggenerated
     */
    public void setPriceLow(Integer priceLow) {
        this.priceLow = priceLow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_series.price_hig
     *
     * @return the value of car_series.price_hig
     *
     * @mbggenerated
     */
    public Integer getPriceHig() {
        return priceHig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_series.price_hig
     *
     * @param priceHig the value for car_series.price_hig
     *
     * @mbggenerated
     */
    public void setPriceHig(Integer priceHig) {
        this.priceHig = priceHig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_series.car_stat
     *
     * @return the value of car_series.car_stat
     *
     * @mbggenerated
     */
    public Byte getCarStat() {
        return carStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_series.car_stat
     *
     * @param carStat the value for car_series.car_stat
     *
     * @mbggenerated
     */
    public void setCarStat(Byte carStat) {
        this.carStat = carStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_series.fetch_url
     *
     * @return the value of car_series.fetch_url
     *
     * @mbggenerated
     */
    public String getFetchUrl() {
        return fetchUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_series.fetch_url
     *
     * @param fetchUrl the value for car_series.fetch_url
     *
     * @mbggenerated
     */
    public void setFetchUrl(String fetchUrl) {
        this.fetchUrl = fetchUrl == null ? null : fetchUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_series.created_at
     *
     * @return the value of car_series.created_at
     *
     * @mbggenerated
     */
    public Integer getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_series.created_at
     *
     * @param createdAt the value for car_series.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Integer createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_series.updated_at
     *
     * @return the value of car_series.updated_at
     *
     * @mbggenerated
     */
    public Integer getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_series.updated_at
     *
     * @param updatedAt the value for car_series.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Integer updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_series.deleted_at
     *
     * @return the value of car_series.deleted_at
     *
     * @mbggenerated
     */
    public Integer getDeletedAt() {
        return deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_series.deleted_at
     *
     * @param deletedAt the value for car_series.deleted_at
     *
     * @mbggenerated
     */
    public void setDeletedAt(Integer deletedAt) {
        this.deletedAt = deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_series.channel
     *
     * @return the value of car_series.channel
     *
     * @mbggenerated
     */
    public Byte getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_series.channel
     *
     * @param channel the value for car_series.channel
     *
     * @mbggenerated
     */
    public void setChannel(Byte channel) {
        this.channel = channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_series.psid
     *
     * @return the value of car_series.psid
     *
     * @mbggenerated
     */
    public Integer getPsid() {
        return psid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_series.psid
     *
     * @param psid the value for car_series.psid
     *
     * @mbggenerated
     */
    public void setPsid(Integer psid) {
        this.psid = psid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_series.channel_2
     *
     * @return the value of car_series.channel_2
     *
     * @mbggenerated
     */
    public String getChannel2() {
        return channel2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_series.channel_2
     *
     * @param channel2 the value for car_series.channel_2
     *
     * @mbggenerated
     */
    public void setChannel2(String channel2) {
        this.channel2 = channel2 == null ? null : channel2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_series.flag
     *
     * @return the value of car_series.flag
     *
     * @mbggenerated
     */
    public Byte getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_series.flag
     *
     * @param flag the value for car_series.flag
     *
     * @mbggenerated
     */
    public void setFlag(Byte flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_series.new_title
     *
     * @return the value of car_series.new_title
     *
     * @mbggenerated
     */
    public String getNewTitle() {
        return newTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_series.new_title
     *
     * @param newTitle the value for car_series.new_title
     *
     * @mbggenerated
     */
    public void setNewTitle(String newTitle) {
        this.newTitle = newTitle == null ? null : newTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_series.new_firm_name
     *
     * @return the value of car_series.new_firm_name
     *
     * @mbggenerated
     */
    public String getNewFirmName() {
        return newFirmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_series.new_firm_name
     *
     * @param newFirmName the value for car_series.new_firm_name
     *
     * @mbggenerated
     */
    public void setNewFirmName(String newFirmName) {
        this.newFirmName = newFirmName == null ? null : newFirmName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_series.liyang_id
     *
     * @return the value of car_series.liyang_id
     *
     * @mbggenerated
     */
    public String getLiyangId() {
        return liyangId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_series.liyang_id
     *
     * @param liyangId the value for car_series.liyang_id
     *
     * @mbggenerated
     */
    public void setLiyangId(String liyangId) {
        this.liyangId = liyangId == null ? null : liyangId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_series.extra_title
     *
     * @return the value of car_series.extra_title
     *
     * @mbggenerated
     */
    public String getExtraTitle() {
        return extraTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_series.extra_title
     *
     * @param extraTitle the value for car_series.extra_title
     *
     * @mbggenerated
     */
    public void setExtraTitle(String extraTitle) {
        this.extraTitle = extraTitle == null ? null : extraTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_series.last_updated_at
     *
     * @return the value of car_series.last_updated_at
     *
     * @mbggenerated
     */
    public Integer getLastUpdatedAt() {
        return lastUpdatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_series.last_updated_at
     *
     * @param lastUpdatedAt the value for car_series.last_updated_at
     *
     * @mbggenerated
     */
    public void setLastUpdatedAt(Integer lastUpdatedAt) {
        this.lastUpdatedAt = lastUpdatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_series.last_updated_user
     *
     * @return the value of car_series.last_updated_user
     *
     * @mbggenerated
     */
    public String getLastUpdatedUser() {
        return lastUpdatedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_series.last_updated_user
     *
     * @param lastUpdatedUser the value for car_series.last_updated_user
     *
     * @mbggenerated
     */
    public void setLastUpdatedUser(String lastUpdatedUser) {
        this.lastUpdatedUser = lastUpdatedUser == null ? null : lastUpdatedUser.trim();
    }
}