package cn.isnap.melon.model;

public class CarType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.level_id
     *
     * @mbggenerated
     */
    private String levelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.brand_id
     *
     * @mbggenerated
     */
    private Short brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.series_id
     *
     * @mbggenerated
     */
    private Short seriesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.type_id
     *
     * @mbggenerated
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.type_title
     *
     * @mbggenerated
     */
    private String typeTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.mfrs
     *
     * @mbggenerated
     */
    private String mfrs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.brand
     *
     * @mbggenerated
     */
    private String brand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.series
     *
     * @mbggenerated
     */
    private String series;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.year
     *
     * @mbggenerated
     */
    private String year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.emission_standard
     *
     * @mbggenerated
     */
    private String emissionStandard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.form
     *
     * @mbggenerated
     */
    private String form;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.classic
     *
     * @mbggenerated
     */
    private String classic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.official_price
     *
     * @mbggenerated
     */
    private String officialPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.release_year
     *
     * @mbggenerated
     */
    private String releaseYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.release_month
     *
     * @mbggenerated
     */
    private String releaseMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.py
     *
     * @mbggenerated
     */
    private String py;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.sy
     *
     * @mbggenerated
     */
    private String sy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.is_in_product
     *
     * @mbggenerated
     */
    private String isInProduct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.orignal_country
     *
     * @mbggenerated
     */
    private String orignalCountry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.is_import
     *
     * @mbggenerated
     */
    private String isImport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.cylinder_volume
     *
     * @mbggenerated
     */
    private String cylinderVolume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.displacement
     *
     * @mbggenerated
     */
    private String displacement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.inlet_form
     *
     * @mbggenerated
     */
    private String inletForm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.fuel_type
     *
     * @mbggenerated
     */
    private String fuelType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.fuel_no
     *
     * @mbggenerated
     */
    private String fuelNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.ps
     *
     * @mbggenerated
     */
    private String ps;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.kw
     *
     * @mbggenerated
     */
    private String kw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.cylinder_arrangement
     *
     * @mbggenerated
     */
    private String cylinderArrangement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.cylinder_num
     *
     * @mbggenerated
     */
    private String cylinderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.valves_num
     *
     * @mbggenerated
     */
    private String valvesNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.transmission_type
     *
     * @mbggenerated
     */
    private String transmissionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.transmission_description
     *
     * @mbggenerated
     */
    private String transmissionDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.gears_num
     *
     * @mbggenerated
     */
    private String gearsNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.front_brake_type
     *
     * @mbggenerated
     */
    private String frontBrakeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.back_brake_type
     *
     * @mbggenerated
     */
    private String backBrakeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.power_assisted_type
     *
     * @mbggenerated
     */
    private String powerAssistedType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.engine_location
     *
     * @mbggenerated
     */
    private String engineLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.drive_system
     *
     * @mbggenerated
     */
    private String driveSystem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.wheelbase
     *
     * @mbggenerated
     */
    private String wheelbase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.doors
     *
     * @mbggenerated
     */
    private String doors;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.seats
     *
     * @mbggenerated
     */
    private String seats;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.front_tire_type
     *
     * @mbggenerated
     */
    private String frontTireType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.back_tire_type
     *
     * @mbggenerated
     */
    private String backTireType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.front_hub_type
     *
     * @mbggenerated
     */
    private String frontHubType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.back_hub_type
     *
     * @mbggenerated
     */
    private String backHubType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.hub_material
     *
     * @mbggenerated
     */
    private String hubMaterial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.spare_wheel_type
     *
     * @mbggenerated
     */
    private String spareWheelType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.electronic_sunroof
     *
     * @mbggenerated
     */
    private String electronicSunroof;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.panorama_sunroof
     *
     * @mbggenerated
     */
    private String panoramaSunroof;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.hid
     *
     * @mbggenerated
     */
    private String hid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.frog_light
     *
     * @mbggenerated
     */
    private String frogLight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.rear_wiper
     *
     * @mbggenerated
     */
    private String rearWiper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.air_condition
     *
     * @mbggenerated
     */
    private String airCondition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.auto_air_condition
     *
     * @mbggenerated
     */
    private String autoAirCondition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.status
     *
     * @mbggenerated
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.level_id
     *
     * @return the value of car_type.level_id
     *
     * @mbggenerated
     */
    public String getLevelId() {
        return levelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.level_id
     *
     * @param levelId the value for car_type.level_id
     *
     * @mbggenerated
     */
    public void setLevelId(String levelId) {
        this.levelId = levelId == null ? null : levelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.brand_id
     *
     * @return the value of car_type.brand_id
     *
     * @mbggenerated
     */
    public Short getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.brand_id
     *
     * @param brandId the value for car_type.brand_id
     *
     * @mbggenerated
     */
    public void setBrandId(Short brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.series_id
     *
     * @return the value of car_type.series_id
     *
     * @mbggenerated
     */
    public Short getSeriesId() {
        return seriesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.series_id
     *
     * @param seriesId the value for car_type.series_id
     *
     * @mbggenerated
     */
    public void setSeriesId(Short seriesId) {
        this.seriesId = seriesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.type_id
     *
     * @return the value of car_type.type_id
     *
     * @mbggenerated
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.type_id
     *
     * @param typeId the value for car_type.type_id
     *
     * @mbggenerated
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.type_title
     *
     * @return the value of car_type.type_title
     *
     * @mbggenerated
     */
    public String getTypeTitle() {
        return typeTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.type_title
     *
     * @param typeTitle the value for car_type.type_title
     *
     * @mbggenerated
     */
    public void setTypeTitle(String typeTitle) {
        this.typeTitle = typeTitle == null ? null : typeTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.mfrs
     *
     * @return the value of car_type.mfrs
     *
     * @mbggenerated
     */
    public String getMfrs() {
        return mfrs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.mfrs
     *
     * @param mfrs the value for car_type.mfrs
     *
     * @mbggenerated
     */
    public void setMfrs(String mfrs) {
        this.mfrs = mfrs == null ? null : mfrs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.brand
     *
     * @return the value of car_type.brand
     *
     * @mbggenerated
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.brand
     *
     * @param brand the value for car_type.brand
     *
     * @mbggenerated
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.series
     *
     * @return the value of car_type.series
     *
     * @mbggenerated
     */
    public String getSeries() {
        return series;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.series
     *
     * @param series the value for car_type.series
     *
     * @mbggenerated
     */
    public void setSeries(String series) {
        this.series = series == null ? null : series.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.type
     *
     * @return the value of car_type.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.type
     *
     * @param type the value for car_type.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.title
     *
     * @return the value of car_type.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.title
     *
     * @param title the value for car_type.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.year
     *
     * @return the value of car_type.year
     *
     * @mbggenerated
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.year
     *
     * @param year the value for car_type.year
     *
     * @mbggenerated
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.emission_standard
     *
     * @return the value of car_type.emission_standard
     *
     * @mbggenerated
     */
    public String getEmissionStandard() {
        return emissionStandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.emission_standard
     *
     * @param emissionStandard the value for car_type.emission_standard
     *
     * @mbggenerated
     */
    public void setEmissionStandard(String emissionStandard) {
        this.emissionStandard = emissionStandard == null ? null : emissionStandard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.form
     *
     * @return the value of car_type.form
     *
     * @mbggenerated
     */
    public String getForm() {
        return form;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.form
     *
     * @param form the value for car_type.form
     *
     * @mbggenerated
     */
    public void setForm(String form) {
        this.form = form == null ? null : form.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.classic
     *
     * @return the value of car_type.classic
     *
     * @mbggenerated
     */
    public String getClassic() {
        return classic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.classic
     *
     * @param classic the value for car_type.classic
     *
     * @mbggenerated
     */
    public void setClassic(String classic) {
        this.classic = classic == null ? null : classic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.official_price
     *
     * @return the value of car_type.official_price
     *
     * @mbggenerated
     */
    public String getOfficialPrice() {
        return officialPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.official_price
     *
     * @param officialPrice the value for car_type.official_price
     *
     * @mbggenerated
     */
    public void setOfficialPrice(String officialPrice) {
        this.officialPrice = officialPrice == null ? null : officialPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.release_year
     *
     * @return the value of car_type.release_year
     *
     * @mbggenerated
     */
    public String getReleaseYear() {
        return releaseYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.release_year
     *
     * @param releaseYear the value for car_type.release_year
     *
     * @mbggenerated
     */
    public void setReleaseYear(String releaseYear) {
        this.releaseYear = releaseYear == null ? null : releaseYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.release_month
     *
     * @return the value of car_type.release_month
     *
     * @mbggenerated
     */
    public String getReleaseMonth() {
        return releaseMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.release_month
     *
     * @param releaseMonth the value for car_type.release_month
     *
     * @mbggenerated
     */
    public void setReleaseMonth(String releaseMonth) {
        this.releaseMonth = releaseMonth == null ? null : releaseMonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.py
     *
     * @return the value of car_type.py
     *
     * @mbggenerated
     */
    public String getPy() {
        return py;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.py
     *
     * @param py the value for car_type.py
     *
     * @mbggenerated
     */
    public void setPy(String py) {
        this.py = py == null ? null : py.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.sy
     *
     * @return the value of car_type.sy
     *
     * @mbggenerated
     */
    public String getSy() {
        return sy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.sy
     *
     * @param sy the value for car_type.sy
     *
     * @mbggenerated
     */
    public void setSy(String sy) {
        this.sy = sy == null ? null : sy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.is_in_product
     *
     * @return the value of car_type.is_in_product
     *
     * @mbggenerated
     */
    public String getIsInProduct() {
        return isInProduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.is_in_product
     *
     * @param isInProduct the value for car_type.is_in_product
     *
     * @mbggenerated
     */
    public void setIsInProduct(String isInProduct) {
        this.isInProduct = isInProduct == null ? null : isInProduct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.orignal_country
     *
     * @return the value of car_type.orignal_country
     *
     * @mbggenerated
     */
    public String getOrignalCountry() {
        return orignalCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.orignal_country
     *
     * @param orignalCountry the value for car_type.orignal_country
     *
     * @mbggenerated
     */
    public void setOrignalCountry(String orignalCountry) {
        this.orignalCountry = orignalCountry == null ? null : orignalCountry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.is_import
     *
     * @return the value of car_type.is_import
     *
     * @mbggenerated
     */
    public String getIsImport() {
        return isImport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.is_import
     *
     * @param isImport the value for car_type.is_import
     *
     * @mbggenerated
     */
    public void setIsImport(String isImport) {
        this.isImport = isImport == null ? null : isImport.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.cylinder_volume
     *
     * @return the value of car_type.cylinder_volume
     *
     * @mbggenerated
     */
    public String getCylinderVolume() {
        return cylinderVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.cylinder_volume
     *
     * @param cylinderVolume the value for car_type.cylinder_volume
     *
     * @mbggenerated
     */
    public void setCylinderVolume(String cylinderVolume) {
        this.cylinderVolume = cylinderVolume == null ? null : cylinderVolume.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.displacement
     *
     * @return the value of car_type.displacement
     *
     * @mbggenerated
     */
    public String getDisplacement() {
        return displacement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.displacement
     *
     * @param displacement the value for car_type.displacement
     *
     * @mbggenerated
     */
    public void setDisplacement(String displacement) {
        this.displacement = displacement == null ? null : displacement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.inlet_form
     *
     * @return the value of car_type.inlet_form
     *
     * @mbggenerated
     */
    public String getInletForm() {
        return inletForm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.inlet_form
     *
     * @param inletForm the value for car_type.inlet_form
     *
     * @mbggenerated
     */
    public void setInletForm(String inletForm) {
        this.inletForm = inletForm == null ? null : inletForm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.fuel_type
     *
     * @return the value of car_type.fuel_type
     *
     * @mbggenerated
     */
    public String getFuelType() {
        return fuelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.fuel_type
     *
     * @param fuelType the value for car_type.fuel_type
     *
     * @mbggenerated
     */
    public void setFuelType(String fuelType) {
        this.fuelType = fuelType == null ? null : fuelType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.fuel_no
     *
     * @return the value of car_type.fuel_no
     *
     * @mbggenerated
     */
    public String getFuelNo() {
        return fuelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.fuel_no
     *
     * @param fuelNo the value for car_type.fuel_no
     *
     * @mbggenerated
     */
    public void setFuelNo(String fuelNo) {
        this.fuelNo = fuelNo == null ? null : fuelNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.ps
     *
     * @return the value of car_type.ps
     *
     * @mbggenerated
     */
    public String getPs() {
        return ps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.ps
     *
     * @param ps the value for car_type.ps
     *
     * @mbggenerated
     */
    public void setPs(String ps) {
        this.ps = ps == null ? null : ps.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.kw
     *
     * @return the value of car_type.kw
     *
     * @mbggenerated
     */
    public String getKw() {
        return kw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.kw
     *
     * @param kw the value for car_type.kw
     *
     * @mbggenerated
     */
    public void setKw(String kw) {
        this.kw = kw == null ? null : kw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.cylinder_arrangement
     *
     * @return the value of car_type.cylinder_arrangement
     *
     * @mbggenerated
     */
    public String getCylinderArrangement() {
        return cylinderArrangement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.cylinder_arrangement
     *
     * @param cylinderArrangement the value for car_type.cylinder_arrangement
     *
     * @mbggenerated
     */
    public void setCylinderArrangement(String cylinderArrangement) {
        this.cylinderArrangement = cylinderArrangement == null ? null : cylinderArrangement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.cylinder_num
     *
     * @return the value of car_type.cylinder_num
     *
     * @mbggenerated
     */
    public String getCylinderNum() {
        return cylinderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.cylinder_num
     *
     * @param cylinderNum the value for car_type.cylinder_num
     *
     * @mbggenerated
     */
    public void setCylinderNum(String cylinderNum) {
        this.cylinderNum = cylinderNum == null ? null : cylinderNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.valves_num
     *
     * @return the value of car_type.valves_num
     *
     * @mbggenerated
     */
    public String getValvesNum() {
        return valvesNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.valves_num
     *
     * @param valvesNum the value for car_type.valves_num
     *
     * @mbggenerated
     */
    public void setValvesNum(String valvesNum) {
        this.valvesNum = valvesNum == null ? null : valvesNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.transmission_type
     *
     * @return the value of car_type.transmission_type
     *
     * @mbggenerated
     */
    public String getTransmissionType() {
        return transmissionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.transmission_type
     *
     * @param transmissionType the value for car_type.transmission_type
     *
     * @mbggenerated
     */
    public void setTransmissionType(String transmissionType) {
        this.transmissionType = transmissionType == null ? null : transmissionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.transmission_description
     *
     * @return the value of car_type.transmission_description
     *
     * @mbggenerated
     */
    public String getTransmissionDescription() {
        return transmissionDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.transmission_description
     *
     * @param transmissionDescription the value for car_type.transmission_description
     *
     * @mbggenerated
     */
    public void setTransmissionDescription(String transmissionDescription) {
        this.transmissionDescription = transmissionDescription == null ? null : transmissionDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.gears_num
     *
     * @return the value of car_type.gears_num
     *
     * @mbggenerated
     */
    public String getGearsNum() {
        return gearsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.gears_num
     *
     * @param gearsNum the value for car_type.gears_num
     *
     * @mbggenerated
     */
    public void setGearsNum(String gearsNum) {
        this.gearsNum = gearsNum == null ? null : gearsNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.front_brake_type
     *
     * @return the value of car_type.front_brake_type
     *
     * @mbggenerated
     */
    public String getFrontBrakeType() {
        return frontBrakeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.front_brake_type
     *
     * @param frontBrakeType the value for car_type.front_brake_type
     *
     * @mbggenerated
     */
    public void setFrontBrakeType(String frontBrakeType) {
        this.frontBrakeType = frontBrakeType == null ? null : frontBrakeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.back_brake_type
     *
     * @return the value of car_type.back_brake_type
     *
     * @mbggenerated
     */
    public String getBackBrakeType() {
        return backBrakeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.back_brake_type
     *
     * @param backBrakeType the value for car_type.back_brake_type
     *
     * @mbggenerated
     */
    public void setBackBrakeType(String backBrakeType) {
        this.backBrakeType = backBrakeType == null ? null : backBrakeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.power_assisted_type
     *
     * @return the value of car_type.power_assisted_type
     *
     * @mbggenerated
     */
    public String getPowerAssistedType() {
        return powerAssistedType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.power_assisted_type
     *
     * @param powerAssistedType the value for car_type.power_assisted_type
     *
     * @mbggenerated
     */
    public void setPowerAssistedType(String powerAssistedType) {
        this.powerAssistedType = powerAssistedType == null ? null : powerAssistedType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.engine_location
     *
     * @return the value of car_type.engine_location
     *
     * @mbggenerated
     */
    public String getEngineLocation() {
        return engineLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.engine_location
     *
     * @param engineLocation the value for car_type.engine_location
     *
     * @mbggenerated
     */
    public void setEngineLocation(String engineLocation) {
        this.engineLocation = engineLocation == null ? null : engineLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.drive_system
     *
     * @return the value of car_type.drive_system
     *
     * @mbggenerated
     */
    public String getDriveSystem() {
        return driveSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.drive_system
     *
     * @param driveSystem the value for car_type.drive_system
     *
     * @mbggenerated
     */
    public void setDriveSystem(String driveSystem) {
        this.driveSystem = driveSystem == null ? null : driveSystem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.wheelbase
     *
     * @return the value of car_type.wheelbase
     *
     * @mbggenerated
     */
    public String getWheelbase() {
        return wheelbase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.wheelbase
     *
     * @param wheelbase the value for car_type.wheelbase
     *
     * @mbggenerated
     */
    public void setWheelbase(String wheelbase) {
        this.wheelbase = wheelbase == null ? null : wheelbase.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.doors
     *
     * @return the value of car_type.doors
     *
     * @mbggenerated
     */
    public String getDoors() {
        return doors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.doors
     *
     * @param doors the value for car_type.doors
     *
     * @mbggenerated
     */
    public void setDoors(String doors) {
        this.doors = doors == null ? null : doors.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.seats
     *
     * @return the value of car_type.seats
     *
     * @mbggenerated
     */
    public String getSeats() {
        return seats;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.seats
     *
     * @param seats the value for car_type.seats
     *
     * @mbggenerated
     */
    public void setSeats(String seats) {
        this.seats = seats == null ? null : seats.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.front_tire_type
     *
     * @return the value of car_type.front_tire_type
     *
     * @mbggenerated
     */
    public String getFrontTireType() {
        return frontTireType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.front_tire_type
     *
     * @param frontTireType the value for car_type.front_tire_type
     *
     * @mbggenerated
     */
    public void setFrontTireType(String frontTireType) {
        this.frontTireType = frontTireType == null ? null : frontTireType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.back_tire_type
     *
     * @return the value of car_type.back_tire_type
     *
     * @mbggenerated
     */
    public String getBackTireType() {
        return backTireType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.back_tire_type
     *
     * @param backTireType the value for car_type.back_tire_type
     *
     * @mbggenerated
     */
    public void setBackTireType(String backTireType) {
        this.backTireType = backTireType == null ? null : backTireType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.front_hub_type
     *
     * @return the value of car_type.front_hub_type
     *
     * @mbggenerated
     */
    public String getFrontHubType() {
        return frontHubType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.front_hub_type
     *
     * @param frontHubType the value for car_type.front_hub_type
     *
     * @mbggenerated
     */
    public void setFrontHubType(String frontHubType) {
        this.frontHubType = frontHubType == null ? null : frontHubType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.back_hub_type
     *
     * @return the value of car_type.back_hub_type
     *
     * @mbggenerated
     */
    public String getBackHubType() {
        return backHubType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.back_hub_type
     *
     * @param backHubType the value for car_type.back_hub_type
     *
     * @mbggenerated
     */
    public void setBackHubType(String backHubType) {
        this.backHubType = backHubType == null ? null : backHubType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.hub_material
     *
     * @return the value of car_type.hub_material
     *
     * @mbggenerated
     */
    public String getHubMaterial() {
        return hubMaterial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.hub_material
     *
     * @param hubMaterial the value for car_type.hub_material
     *
     * @mbggenerated
     */
    public void setHubMaterial(String hubMaterial) {
        this.hubMaterial = hubMaterial == null ? null : hubMaterial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.spare_wheel_type
     *
     * @return the value of car_type.spare_wheel_type
     *
     * @mbggenerated
     */
    public String getSpareWheelType() {
        return spareWheelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.spare_wheel_type
     *
     * @param spareWheelType the value for car_type.spare_wheel_type
     *
     * @mbggenerated
     */
    public void setSpareWheelType(String spareWheelType) {
        this.spareWheelType = spareWheelType == null ? null : spareWheelType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.electronic_sunroof
     *
     * @return the value of car_type.electronic_sunroof
     *
     * @mbggenerated
     */
    public String getElectronicSunroof() {
        return electronicSunroof;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.electronic_sunroof
     *
     * @param electronicSunroof the value for car_type.electronic_sunroof
     *
     * @mbggenerated
     */
    public void setElectronicSunroof(String electronicSunroof) {
        this.electronicSunroof = electronicSunroof == null ? null : electronicSunroof.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.panorama_sunroof
     *
     * @return the value of car_type.panorama_sunroof
     *
     * @mbggenerated
     */
    public String getPanoramaSunroof() {
        return panoramaSunroof;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.panorama_sunroof
     *
     * @param panoramaSunroof the value for car_type.panorama_sunroof
     *
     * @mbggenerated
     */
    public void setPanoramaSunroof(String panoramaSunroof) {
        this.panoramaSunroof = panoramaSunroof == null ? null : panoramaSunroof.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.hid
     *
     * @return the value of car_type.hid
     *
     * @mbggenerated
     */
    public String getHid() {
        return hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.hid
     *
     * @param hid the value for car_type.hid
     *
     * @mbggenerated
     */
    public void setHid(String hid) {
        this.hid = hid == null ? null : hid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.frog_light
     *
     * @return the value of car_type.frog_light
     *
     * @mbggenerated
     */
    public String getFrogLight() {
        return frogLight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.frog_light
     *
     * @param frogLight the value for car_type.frog_light
     *
     * @mbggenerated
     */
    public void setFrogLight(String frogLight) {
        this.frogLight = frogLight == null ? null : frogLight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.rear_wiper
     *
     * @return the value of car_type.rear_wiper
     *
     * @mbggenerated
     */
    public String getRearWiper() {
        return rearWiper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.rear_wiper
     *
     * @param rearWiper the value for car_type.rear_wiper
     *
     * @mbggenerated
     */
    public void setRearWiper(String rearWiper) {
        this.rearWiper = rearWiper == null ? null : rearWiper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.air_condition
     *
     * @return the value of car_type.air_condition
     *
     * @mbggenerated
     */
    public String getAirCondition() {
        return airCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.air_condition
     *
     * @param airCondition the value for car_type.air_condition
     *
     * @mbggenerated
     */
    public void setAirCondition(String airCondition) {
        this.airCondition = airCondition == null ? null : airCondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.auto_air_condition
     *
     * @return the value of car_type.auto_air_condition
     *
     * @mbggenerated
     */
    public String getAutoAirCondition() {
        return autoAirCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.auto_air_condition
     *
     * @param autoAirCondition the value for car_type.auto_air_condition
     *
     * @mbggenerated
     */
    public void setAutoAirCondition(String autoAirCondition) {
        this.autoAirCondition = autoAirCondition == null ? null : autoAirCondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.status
     *
     * @return the value of car_type.status
     *
     * @mbggenerated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.status
     *
     * @param status the value for car_type.status
     *
     * @mbggenerated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.remark
     *
     * @return the value of car_type.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.remark
     *
     * @param remark the value for car_type.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}